### PR TITLE
Update SPECIFICATION-DOCUMENT-REQUIREMENTS.md

### PR DESCRIPTION
**Pull request by chaals**
require security considerations, etc, and change list for Spec Draft status

### CODE REVIEW

**Comment by tkuhrt** [comment]
Should the two changes be converted to a MUST?

**Comment by chaals** [comment]
@tkuhrt noticed:

> Should the two changes be converted to a MUST?

Oops. Yep. Done in 2d616a9

**Review by tkuhrt — APPROVED** [review]
LGTM

**Review by DONALDSULLENDER — APPROVED** [review]

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by burnburn** [comment]
Approved by PGB.  Merging.

**Pull request merged**
